source 'https://rubygems.org'

#ruby=ruby-2.2.1@convert_service

gem 'awesome_print'
gem 'daemons'
gem 'passenger'
gem 'figaro'
gem 'minitest'
gem 'haml'
gem 'i18n'
gem 'json'
gem 'pg'
gem 'rack'
gem 'rake'
gem 'rest-client'
gem 'rerun'
gem 'rspec'
gem 'sequel'
gem 'process_shared'
gem 'sqlite3'
gem 'sinatra'
gem 'sinatra-contrib'